version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/golemfactory/bootstrap_go

    steps:
      - checkout

      - run: go get golang.org/x/tools/cmd/goimports
      - run: if [[ $(goimports -l . | wc -c) -ne 0 ]]; then echo "Files are not formatted, run goimports"; exit 1; fi

      - run: go get -v -t ./...
      - run: go test -v -race ./...
      - run: go vet -v ./...
